### ISSUE TITLE
supplier_tester sends booking request with the same oder_reference

### ISSUE THREAD

**Issue by lounerios** [Tiqets/supplier-api#53]
The booking request sends the same order_reference codes (123456, 12345678910).
However our booking system needs unique reference codes, so this behavior of the supplier_tester causes some problems

**Comment by mennobb** [comment]
Hi Lounerios, a task to change this behavior has been created but it'll be a while before we can pick this up.
In the meanwhile, as a work-around maybe modify your references internally after finishing a test round.
That way the next test round won't run into collisions as it uses the 123456... refs again.

**Comment by trojkat** [comment]
It was fixed in #55, thanks for reporting.
