### ISSUE TITLE
Incorrect status code "403" when calling the API via method GET

### ISSUE THREAD

**Issue by AEiosApp** [Tiqets/supplier-api#94]
We are testing Supplier API integration via [https://supplier-api-web-tool.tiqets.com/](https://supplier-api-web-tool.tiqets.com/) 

One of the tests makes **GET** request with **request body** and require response status code **405**.

However, since a lot of API services (including **AWS API Gateway** that we are using) do not support GET requests with a request body - they block such requests with a built in mechanisms that we do not control. And in our case AWS API Gateway respond with a status code **403**.

[https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#RequestCustom-get-body](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#RequestCustom-get-body)

<img width="1440" alt="Screenshot 2023-10-02 at 11 57 26 AM" src="https://github.com/Tiqets/supplier-api/assets/19554725/b78383d1-950f-405c-a312-97373a463a63">

 
Same test with PUT/PATCH/DELETE request we can handle successfully with a response code **405**

**Our question is:**
- is it possible to exclude GET request with a request body from supplier API tool?
OR
- can our integration be approved excluding this test case?

<img width="1440" alt="Screenshot 2023-09-24 at 1 25 17 PM" src="https://github.com/Tiqets/supplier-api/assets/19554725/24e0fa9d-5350-4d55-a811-c9941dc328ab">

**Comment by trojkat** [comment]
@AEiosApp we already dropped all the tests for not allowed methods.
